# Project: MaqVendas
# Makefile created by Dev-C++ 5.8.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o maqvenda.o
LINKOBJ  = main.o maqvenda.o
LIBS     = -L"C:/Users/pedro.rech/Documents/Dev-Cpp/Dev-Cpp/MinGW64/lib" -L"C:/Users/pedro.rech/Documents/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/pedro.rech/Documents/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"C:/Users/pedro.rech/Documents/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/pedro.rech/Documents/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/pedro.rech/Documents/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"C:/Users/pedro.rech/Documents/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/pedro.rech/Documents/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/pedro.rech/Documents/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = MaqVendas.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

maqvenda.o: maqvenda.cpp
	$(CPP) -c maqvenda.cpp -o maqvenda.o $(CXXFLAGS)
